### ISSUE TITLE
Title change description isn't working 

### ISSUE THREAD

**Issue by BjoernPetersen** [torbencarstens/hhh-diff-bot#13]
If group "A" is renamed to "B", the change will be described as "B -> B" instead of the correct "A -> B".

**Comment by torbencarstens** [comment]
Interestingly enough, this doesn't always happen

Pulled from the production version:
```
test234 -> New Group
Added test234```

I think it has something to do with the internal `chat_data` state from the bot (sdk controlled).

I've added this https://github.com/torbencarstens/hhh-diff-bot/blob/master/telegram_bot/decorators.py#L67-L68 to avoid having missing titles (which was what happened before).

**Comment by torbencarstens** [comment]
Maybe this https://github.com/torbencarstens/hhh-diff-bot/blob/master/telegram_bot/bot.py#L209 fucks with the internal state. AFAIK it shouldn't, but I should try it out.

Rename a group -> This should work correctly when starting the bot.
Remove the bot from another group
Rename a group -> The problem should occur here if that is the problem.

I don't have a fix for this on hand, I'd have to read deeper into the documentation for chat_data.

**Comment by torbencarstens** [comment]
```
E wie Elefant -> E wie Elefant
beer ratings -> beer ratings
```

This theory went down the drain (most likely).

**Comment by torbencarstens** [comment]
#17 seems to have fixed this.
