### ISSUE TITLE
I wanna do code reviews before deployment :)

### ISSUE THREAD

**Issue by BjoernPetersen** [torbencarstens/hhh-diff-bot#2]

**Comment by torbencarstens** [comment]
![image](https://user-images.githubusercontent.com/7738181/87937524-31a42400-ca95-11ea-971a-1e6334fa2974.png)
in addition to 3a65c3c731177fa892d2350166973c361d7763b1 and me setting `branch.master.remote no_push`  in my local .gitconfig should "enforce" this.
