### ISSUE TITLE
Change group delimiter

### ISSUE THREAD

**Issue by torbencarstens** [torbencarstens/hhh-diff-bot#9]
The delimiter for groups with the same starting letter is currently `,`, there are too many groups which name contains one -> Makes it unclear where the groups ends.

Possibly `;`?

**Comment by BjoernPetersen** [comment]
I was particularly fond of "Chip und Chap, Cicker, Cohle, Comedy, Corona, Creuzigungen, Cästenwetten" though

**Comment by torbencarstens** [comment]
That's what inspired me
